# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GalleryGuide’ do
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~> 4.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.1'
end
